baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "Harshit Joshi"

DefaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 15  # Maximum number of items in the RSS feed.
copyright = "License Message" # This message is only used by the RSS template.

googleAnalytics = "G-T6EYX1WEB9"
disqusShortname = "joshiharshit-com"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

#[author]
#  name = "Harshit Joshi"
#  description = "Tech Professional"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"


[params]

  [params.author]
    name = "Harshit Joshi"

  homeSubtitle = "Harshit Joshi"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Harshit Joshi"
  keywords = "homepage, blog, software, cloud, development, programming, coding, machine learning, ML, AI"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []
  
  [params.footer]
    trademark = 2025
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = ["A year from now, you will wish you had started today. </br><a href=\"https://t.co/Wor3sMJ3DQ?amp=1\">A Reason To Stop Worrying &#10084;</a>"]

  [[params.social]]
    name = "email"
    url  = "mailto:hpj1992@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/hpj1992"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/harshitjoshi1/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/2254097/harshit"

  [[params.social]]
    name = "dev"
    url  = "https://dev.to/hpj1992"  

  [[params.social]]
    name = "medium"
    url  = "https://joshiharshit.medium.com/"

  [[params.social]]
    name = "unsplash"
    url  = "https://unsplash.com/@hpj1992"    

[languages]
  [languages.en]
    title = "Harshit Joshi"
    subtitle = "Portfolio And Blogs"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "~/home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
    

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blogs"
        url = "/posts"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts/"
